### ISSUE TITLE
Code error from cloudformation.py and ec2.py

### ISSUE THREAD

**Issue by ben-le** [codemonauts/aws-springcleaning#15]
So far, everything is working perfectly, except for the below error messages.

**First error message regarded cloudformation.py**

File "/home/ubuntu/SDK_boto3/aws-springcleaning/modules/cloudformation.py", line 4, in <module>
    from config import REGIONS, CF_STACK_OLD_DAYS
ImportError: cannot import name 'CF_STACK_OLD_DAYS' from 'config' (/home/ubuntu/SDK_boto3/aws-springcleaning/config.py)

Caused by missing the "CF_STACK_OLD_DAYS" in config.py. Resolved by add "CF_STACK_OLD_DAYS = 100" in the config.py file

**Second error message regarded EC2.py**

Traceback (most recent call last):
  File "full_scan.py", line 53, in <module>
    ec2.scan()
  File "/home/ubuntu/SDK_boto3/aws-springcleaning/modules/ec2.py", line 36, in scan
    name = [t["Value"] for t in i["Tags"] if t["Key"] == "Name"][0]
KeyError: 'Tags'

Caused by some EC2 Instances are missing the Tag(Name). Resolved by add (Tag/Name) to that particular EC2 instance.

**Third error message regarded cloudformation.py**

Traceback (most recent call last):
  File "./full_scan.py", line 74, in <module>
    cloudformation.scan()
  File "/home/ubuntu/SDK_boto3/aws-springcleaning/modules/cloudformation.py", line 26, in scan
    age = now - s["LastUpdatedTime"]
KeyError: 'LastUpdatedTime'

Caused by some of the cloudformation stacks don't have the timestamp updated.

**Comment by fleaz** [comment]
Hey @ben-le, 

thanks for reporting all the issues and sorry for the bad code quality.

All the bugs have been fixed in the last few commits: f27da6639098025a8d854e731d6a8ad5a0321bf8 40bca70029f4661dc7d9c9ef7fc28db43fb6c8a2 3c4812c7885745d946404d0e7191b8abdcdf9e89

If you find more bugs or have ideas to make this better or more helpful, I'm looking forward to new issues :)

Best regards,
Felix
